### ISSUE TITLE
How to change port

### ISSUE THREAD

**Issue by mathisloevenich** [tiagoporto/vue-todo#4]
Hey I would like to know how to run this on a different port. 

Likely port=80 to create a simple local dns entry. 

Would be nice to have other configuration set as well.

Blame me if I am wrong but there is no obvious `config.conf` file or so to do this. 

I would recommend to update the README on this

**Comment by tiagoporto** [comment]
Hi @mathisloevenich this project uses [vue-cli](https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-serve).

Go to `package.json`

Change
```md
"start": "vue-cli-service serve"
```

To
```md
"start": "vue-cli-service serve --port 80"
```
